algoritmo "Entrada e Saida de Dados"
// Função :
// Autor :
// Data : 18/11/2020
// Seção de Declarações 
var
   nome: caractere
   nota1, nota2, media: real

inicio
// Seção de Comandos
   escreval ("Digite o seu nome:")
   leia(nome)
   
   escreval ("Digite sua primeira nota:")
   leia(nota1)
   escreval ("Digite sua segunda nota:")
   leia(nota2)
   
   media <- (nota1 + nota2)/2
   
   escreval ("O nome digitado foi: ", nome)
   escreval ("A media foi: ", media)
 
fimalgoritmo
