algoritmo "estrutura-Para-faca"
// Função :
// Autor :
// Data : 23/11/2020
// Seção de Declarações 
var
   numero, fatorial, contador: inteiro

inicio
// Seção de Comandos
   escreva("Escreva o número para calcular o fatorial")
   leia(numero)
   fatorial := 1
   
   para contador de 1 ate numero faca
        fatorial := fatorial * contador
   fimpara
   escreva ("O fatorial de ", numero, " é: ", fatorial)
 
fimalgoritmo
